const icons={
  'arrow-right':'<svg viewBox="0 0 24 24"><path d="M5 12h13M13 6l6 6-6 6"/></svg>',
  'arrow-up-right':'<svg viewBox="0 0 24 24"><path d="M7 17 17 7M8 7h9v9"/></svg>',
  'pulse':'<svg viewBox="0 0 24 24"><path d="M3 12h4l2-7 4 14 2-7h6"/></svg>',
  'shield':'<svg viewBox="0 0 24 24"><path d="M12 3 20 6v5c0 5-3.4 8.5-8 10-4.6-1.5-8-5-8-10V6l8-3Z"/><path d="m9 12 2 2 4-4"/></svg>',
  'spark':'<svg viewBox="0 0 24 24"><path d="m12 3 1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8L12 3ZM19 16l.8 2.2L22 19l-2.2.8L19 22l-.8-2.2L16 19l2.2-.8L19 16Z"/></svg>',
  'whatsapp':'<img src="https://ddpavidedetizadora.com/assets/icones/whatsapp%20branco.png" alt="">'
};
document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icons[el.dataset.icon]||''});
const favicon=document.createElement('link');favicon.rel='icon';favicon.type='image/png';favicon.href='logo-equilibrium-icon-clean.png';document.head.appendChild(favicon);
const whatsappStyle=document.createElement('style');whatsappStyle.textContent='.whatsapp-float{position:fixed;right:36px;bottom:30px;z-index:10;width:58px;height:58px;display:grid;place-items:center;background:#25d366;color:#fff;border:0;border-radius:50%;box-shadow:0 15px 34px rgba(37,211,102,.48),0 0 0 3px rgba(37,211,102,.24);transition:transform .25s ease,box-shadow .25s ease;animation:whatsapp-float 3.2s ease-in-out infinite}.whatsapp-float:hover{transform:translateY(-4px) scale(1.05);box-shadow:0 18px 38px rgba(37,211,102,.55),0 0 0 4px rgba(37,211,102,.28);animation-play-state:paused}.whatsapp-float .icon{width:28px;height:28px}.whatsapp-float .icon img{display:block;width:28px;height:28px;object-fit:contain}.whatsapp-label{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}@keyframes whatsapp-float{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}';document.head.appendChild(whatsappStyle);
const logoStyle=document.createElement('style');logoStyle.textContent='.logo-icon-only{display:block;position:relative;width:58px;height:58px;overflow:hidden;background:transparent}.logo-icon-only img{display:block;width:100%;height:100%;object-fit:contain;max-width:none;image-rendering:auto}.footer-brand .logo-icon-only{width:84px;height:66px}.footer-brand .logo-icon-only img{width:84px;height:66px;object-fit:fill}.brand{gap:0}@media(max-width:850px){.logo-icon-only{width:52px;height:52px}.footer-brand .logo-icon-only{width:76px;height:60px}.footer-brand .logo-icon-only img{width:76px;height:60px}}';document.head.appendChild(logoStyle);
const buttonStyle=document.createElement('style');buttonStyle.textContent='.button{border-radius:999px;padding:16px 23px;box-shadow:0 8px 20px rgba(23,60,67,.12);transition:transform .35s cubic-bezier(.22,1,.36,1),box-shadow .35s cubic-bezier(.22,1,.36,1),background-color .35s ease}.button:hover{transform:translate3d(0,-3px,0);box-shadow:0 13px 28px rgba(23,60,67,.18)}.button-primary{box-shadow:0 8px 20px rgba(15,156,155,.22)}.button-primary:hover{box-shadow:0 13px 28px rgba(15,156,155,.3)}.button-light{box-shadow:0 8px 20px rgba(23,42,46,.12)}.button-light:hover{box-shadow:0 13px 28px rgba(23,42,46,.2)}.header-action{border:1px solid rgba(15,156,155,.25);border-radius:999px;padding:10px 14px;transition:background-color .3s ease,transform .3s ease,box-shadow .3s ease}.header-action:hover{background:rgba(15,156,155,.08);transform:translateY(-2px);box-shadow:0 7px 16px rgba(15,156,155,.12)}';document.head.appendChild(buttonStyle);
const header=document.querySelector('[data-site-header]');
if(header){header.innerHTML=`<header class="site-header"><a class="brand" href="index.html"><span class="logo-icon-only"><img src="logo-equilibrium-icon.png" alt="Equilibrium Multi"></span></a><button class="menu-toggle" aria-label="Abrir menu" aria-expanded="false"><span></span><span></span><span></span></button><nav class="main-nav"><a href="index.html">Início</a><a href="servicos.html">Serviços</a><a href="equipe.html">Quem somos</a><a href="contato.html" class="header-action">Fale conosco <span class="icon" data-icon="arrow-up-right"></span></a></nav></header>`;document.querySelectorAll('.main-nav [data-icon]').forEach(el=>el.innerHTML=icons[el.dataset.icon]);const toggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.main-nav');toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});const current=location.pathname.split('/').pop()||'index.html';document.querySelectorAll('.main-nav a').forEach(a=>{if(a.getAttribute('href')===current)a.classList.add('active')})}
const motionStyle=document.createElement('style');motionStyle.textContent='.reveal{opacity:0;transform:translate3d(0,22px,0);will-change:opacity,transform;transition:opacity .72s cubic-bezier(.22,1,.36,1),transform .72s cubic-bezier(.22,1,.36,1)}.reveal.visible{opacity:1;transform:translate3d(0,0,0)}.service-grid .reveal:nth-child(2),.team-grid .reveal:nth-child(2),.values-grid .reveal:nth-child(2){transition-delay:.08s}.service-grid .reveal:nth-child(3),.team-grid .reveal:nth-child(3),.values-grid .reveal:nth-child(3){transition-delay:.16s}.service-grid .reveal:nth-child(4),.team-grid .reveal:nth-child(4){transition-delay:.24s}.button,.text-link,.circle-link,.service-card,.team-card img,.whatsapp-float{transition-timing-function:cubic-bezier(.22,1,.36,1)}.button:focus-visible,.text-link:focus-visible,.circle-link:focus-visible,.service-card:focus-visible,.main-nav a:focus-visible,.whatsapp-float:focus-visible{outline:3px solid rgba(231,111,81,.72);outline-offset:4px}.service-card,.team-card img{will-change:transform}.service-card:hover{transform:translate3d(0,-6px,0)}.team-card:hover img{transform:scale(1.025)}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.reveal,.reveal.visible,.service-card,.team-card img,.whatsapp-float{animation:none!important;transition:none!important;transform:none!important;opacity:1!important;will-change:auto}}';document.head.appendChild(motionStyle);const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12,rootMargin:'0px 0px -8% 0px'});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const footer=document.querySelector('[data-site-footer]');if(footer){footer.innerHTML=`<footer class="site-footer"><div class="footer-main"><div><a class="brand footer-brand" href="index.html"><span class="logo-icon-only"><img src="logo-equilibrium-icon.png" alt="Equilibrium Multi"></span></a><p class="footer-intro">Cuidado preciso, humano e em movimento para organizações e profissionais de saúde.</p></div><div class="footer-column"><h3>Explorar</h3><a href="servicos.html">Serviços</a><a href="equipe.html">Quem somos</a><a href="contato.html">Contato</a></div><div class="footer-column"><h3>Converse</h3><a href="mailto:contato@equilibriummulti.com.br">contato@equilibriummulti.com.br</a><a href="tel:+5511967228000">(11) 96722-8000</a><a href="https://wa.me/5511967228000" target="_blank" rel="noopener">WhatsApp</a></div></div><div class="footer-bottom"><span>© 2026 Equilibrium Multi Serviços de Saúde</span><a href="privacidade.html">Política de privacidade / LGPD</a></div></footer>`}
if(footer){footer.querySelectorAll('.footer-main>div,.footer-bottom').forEach(el=>{el.classList.add('reveal');observer.observe(el)})}
document.querySelectorAll('.logo-icon-only img').forEach(image=>{image.src='logo-equilibrium-icon-clean.png'});
const form=document.querySelector('[data-contact-form]');if(form){form.addEventListener('submit',event=>{event.preventDefault();const message=form.querySelector('.success-message');message.classList.add('visible');form.reset()})}
